### ISSUE TITLE
Please review require_login_in_context_ajax

### ISSUE THREAD

**Issue by danmarsden** [Opencast-Moodle/moodle-local_chunkupload#10]
What's the use-case for a CONTEXT_SYSTEM with forcelogin off to allow anonymous user uploads? - in that scenario the require_login() check is completely bypassed.

**Comment by Laur0r** [comment]
@justusdieckmann we just looked over it, do you see any reasons why we shouldn't delete lines 60-64 and handle everything with the else case in line 65/66 in login-helper.php (https://github.com/Opencast-Moodle/moodle-local_chunkupload/blob/0b6136478e87b103ebbe6c689de07f8fff6735fa/classes/login_helper.php#L66)?

**Comment by Laur0r** [comment]
Closed by #17
