### ISSUE TITLE
incorrect way to check if user is logged in as guest

### ISSUE THREAD

**Issue by danmarsden** [Opencast-Moodle/moodle-local_chunkupload#12]
https://github.com/learnweb/moodle-local_chunkupload/blob/master/classes/chunkupload_form_element.php#L240

better to use the core api "isguestuser()"

and... that also makes me think that your require_login_in_context_ajax should be forcing login even when $cfg->forcelogin is not set. (Issue #10)

**Comment by justusdieckmann** [comment]
Fixed by #15, thanks :)
