### ISSUE TITLE
Start time of video in Opencast is one hour ahead

### ISSUE THREAD

**Issue by Arnei** [Opencast-Moodle/moodle-local_chunkupload#19]
When adding a video, the start time in Opencast will differ by +1 hour from the time set in Moodle. The +1 difference seems to stay consistent when changing timezones in Moodle.

![Bildschirmfoto vom 2021-02-09 12-37-48](https://user-images.githubusercontent.com/14070005/107359846-78ab4280-6ad5-11eb-8018-9b4ea52bcb90.png)
![Bildschirmfoto vom 2021-02-09 12-38-07](https://user-images.githubusercontent.com/14070005/107359840-777a1580-6ad5-11eb-9133-dab928e5ed20.png)

**Comment by t-schroeder** [comment]
This is an issue with block_opencast, not with this plugin.

**Comment by Arnei** [comment]
My apologies, thanks for the information. Then I will close this. ([Related issue over in the block_opencast repo](https://github.com/Opencast-Moodle/moodle-block_opencast/issues/148))
